### ISSUE TITLE
Provide a new option for the user to upload the file to nextcloud from SEAGrid Rich client

### ISSUE THREAD

**Issue by karankotz** [airavata-courses/airavata-nextcoud#3]
Provide the option for the users to pre-stage the file to the Nextcloud in the client. So, in the context when users are creating the experiment they should be able to see this file with the new interface window which will fetch the files and display in the nextcloud interface.

**Comment by pkmsoftpro** [comment]
https://github.com/airavata-courses/airavata-nextcoud/commit/6eaf83a785a3435949684e70d19f7a18b4f5a940
