### ISSUE TITLE
Project Milestone 2 review

### ISSUE THREAD

**Issue by hardikrakholiya** [airavata-courses/airavata-nextcoud#41]

**Comment by hardikrakholiya** [comment]
I saw your demo video in the class and once more after the class. I wasn't sure of how to review the your project since project goals like service discovery, async communication, CI/CD weren't explicitly implemented. I asked the prof. Suresh Marru and he told me the project using Airavata have a little liberty considering the complexity involved. Setting up airavata itself takes up so much time. So that clears my doubts. 

About the review, I saw in video certain notifications popping up in SeaGrid desktop client. That should have been done with async communication. Also job status was been changed asynchronously whenever it changed. Although, I dont have SeaGrid desktop client setup on my system. I was able login into Airavata-Nextcloud using credentials provided and followed the related steps shown in the demo video. I could see the experiment files uploaded earlier. I was getting 'Access Forbidden' when I tried to see external storage being used. Overall, the product looks great and is close to the real products we use everyday. 

I just have one suggestion regarding the demo video. Video is long and that is fine. But if the narrator were vocal, we would understand the features better. It would also be easier to keep track of whatever was going on. Make a demo like you were selling your product to a panel of investors, like in Shark Tank TV show.

**Comment by karankotz** [comment]
@hardikrakholiya Please tell me the credentials that you are using to test for the nextcloud, I had given you the test credentials that didn't have the access to the external storage folder (test-airavata - username). Now you should be able to access the external storage folder using this account. 
Let me know if you have any issues.
