### ISSUE TITLE
Project milestone 2 review 

### ISSUE THREAD

**Issue by jitendraselvam** [airavata-courses/airavata-nextcoud#42]
I saw the uploaded video and I would like to make a small suggestion. 

problem:
Since the video is quite long, one can easily loose track of what is going on in the video. 

my suggestion:
You could add textual information while performing actions in the video so that it could help us better understand what is going on in the video.

**Comment by karankotz** [comment]
@jitendraselvam Next time if we are going to upload the video we are going to take care of the same.
