### ISSUE TITLE
Peer review Project 4

### ISSUE THREAD

**Issue by hardikrakholiya** [airavata-courses/airavata-nextcoud#56]
can you guys share the access token for kubernetes dashboard via email?

**Comment by karankotz** [comment]
@hardikrakholiya you can click "Skip" and continue to view the dashboard.

**Comment by hardikrakholiya** [comment]
Good job on providing clear and consice documentation. I can see your updated architecure and evolution of the project through this semester. Most of all I like how you  providing steps for installing kubernetes cluster on jetstream centOS instance and on KubeNow. I have followed similar steps so this could have provided me help if I had looked at those earlier. I was able to login into Nextcloud and was able to test it without any issues. I also looked at the kubernetes dashboard and was able to see the deployed pods.
